In [3]:
import pandas as pd

df = pd.read_csv("data/Fraud_Data.csv")
print(df.shape)
df.head()

(151112, 11)

   user_id          signup_time        purchase_time  purchase_value  ... sex age    ip_address class
0    22058  2015-02-24 22:55:49  2015-04-18 02:47:11              34  ...   M  39  7.327584e+08     0
1   333320  2015-06-07 20:39:50  2015-06-08 01:38:54              16  ...   F  53  3.503114e+08     0
2     1359  2015-01-01 18:52:44  2015-01-01 18:52:45              15  ...   M  53  2.621474e+09     1
3   150084  2015-04-28 21:13:25  2015-05-04 13:54:50              44  ...   M  41  3.840542e+09     0
4   221365  2015-07-21 07:09:52  2015-09-09 18:40:53              39  ...   M  45  4.155831e+08     0

[5 rows x 11 columns]

In [7]:
df['signup_time'] = pd.to_datetime(df['signup_time'])
df['purchase_time'] = pd.to_datetime(df['purchase_time'])

df['seconds_to_buy'] = (df['purchase_time'] - df['signup_time']).dt.total_seconds()

df.head()

   user_id         signup_time       purchase_time  purchase_value  ... age    ip_address class seconds_to_buy
0    22058 2015-02-24 22:55:49 2015-04-18 02:47:11              34  ...  39  7.327584e+08     0      4506682.0
1   333320 2015-06-07 20:39:50 2015-06-08 01:38:54              16  ...  53  3.503114e+08     0        17944.0
2     1359 2015-01-01 18:52:44 2015-01-01 18:52:45              15  ...  53  2.621474e+09     1            1.0
3   150084 2015-04-28 21:13:25 2015-05-04 13:54:50              44  ...  41  3.840542e+09     0       492085.0
4   221365 2015-07-21 07:09:52 2015-09-09 18:40:53              39  ...  45  4.155831e+08     0      4361461.0

[5 rows x 12 columns]

In [13]:
median = df.groupby("class")['seconds_to_buy'].median()

In [12]:
df["class"].value_counts()

class
0    136961
1     14151
Name: count, dtype: int64

In [14]:
print(median/3600)
print(median/86400)

class
0    1443.030833
1       0.000278
Name: seconds_to_buy, dtype: float64
class
0    60.126285
1     0.000012
Name: seconds_to_buy, dtype: float64

In [20]:
df['instant_buy'] = df['seconds_to_buy'] <= 1
df.groupby('class')['instant_buy'].mean()

class
0    0.000000
1    0.537065
Name: instant_buy, dtype: float64

In [21]:
df.head(2)

   user_id         signup_time       purchase_time  purchase_value  ...    ip_address class seconds_to_buy instant_buy
0    22058 2015-02-24 22:55:49 2015-04-18 02:47:11              34  ...  7.327584e+08     0      4506682.0       False
1   333320 2015-06-07 20:39:50 2015-06-08 01:38:54              16  ...  3.503114e+08     0        17944.0       False

[2 rows x 13 columns]

In [26]:
df['device_user_count'] = df.groupby('device_id')['user_id'].transform('nunique')
df['device_user_count'].value_counts().sort_index()
df.groupby('device_user_count')['class'].mean()

device_user_count
1     0.030429
2     0.229022
3     0.244444
4     0.625000
5     0.800000
6     0.827586
7     0.860000
8     0.875000
9     0.888889
10    0.898913
11    0.908191
12    0.918519
13    0.921875
14    0.927318
15    0.923577
16    0.934028
17    0.936652
18    0.938889
19    0.947368
20    0.950000
Name: class, dtype: float64

In [27]:
df['ip_user_count'] = df.groupby('ip_address')['user_id'].transform('nunique')
df.groupby('ip_user_count')['class'].mean()

ip_user_count
1     0.045653
2     0.500000
3     0.666667
4     0.812500
5     0.800000
6     0.838889
7     0.865714
8     0.878521
9     0.897019
10    0.902247
11    0.914545
12    0.920330
13    0.927885
14    0.932203
15    0.933333
16    0.939236
17    0.941176
18    0.944444
19    0.954887
20    0.950000
Name: class, dtype: float64

In [28]:
df['purchase_hour'] = df['purchase_time'].dt.hour
df['purchase_weekday'] = df['purchase_time'].dt.dayofweek
df.groupby('purchase_hour')['class'].mean().round(3)

purchase_hour
0     0.089
1     0.090
2     0.092
3     0.095
4     0.083
5     0.090
6     0.093
7     0.088
8     0.101
9     0.106
10    0.100
11    0.089
12    0.094
13    0.091
14    0.095
15    0.099
16    0.099
17    0.107
18    0.096
19    0.097
20    0.082
21    0.091
22    0.085
23    0.093
Name: class, dtype: float64

In [30]:
df.head()

   user_id         signup_time       purchase_time  ...  ip_user_count purchase_hour purchase_weekday
0    22058 2015-02-24 22:55:49 2015-04-18 02:47:11  ...              1             2                5
1   333320 2015-06-07 20:39:50 2015-06-08 01:38:54  ...              1             1                0
2     1359 2015-01-01 18:52:44 2015-01-01 18:52:45  ...             12            18                3
3   150084 2015-04-28 21:13:25 2015-05-04 13:54:50  ...              1            13                0
4   221365 2015-07-21 07:09:52 2015-09-09 18:40:53  ...              1            18                2

[5 rows x 17 columns]

In [32]:
ip = pd.read_csv('data/IpAddress_to_Country.csv')
ip['lower_bound_ip_address'] = ip['lower_bound_ip_address'].astype(float)
ip = ip.sort_values('lower_bound_ip_address')
df = df.sort_values('ip_address')

df = pd.merge_asof(df, ip,
                   left_on='ip_address',
                   right_on='lower_bound_ip_address',
                   direction='backward')

df.loc[df['ip_address'] > df['upper_bound_ip_address'], 'country'] = 'Unknown'
df['country'] = df['country'].fillna('Unknown')
df = df.drop(columns=['lower_bound_ip_address', 'upper_bound_ip_address']).reset_index(drop=True)

print('country' in df.columns)
df['country'].value_counts().head()

True

country
United States     58049
Unknown           21966
China             12038
Japan              7306
United Kingdom     4490
Name: count, dtype: int64

In [33]:
top_countries = df['country'].value_counts().head(10).index
df['country_grp'] = df['country'].where(df['country'].isin(top_countries), 'Other')
df['country_grp'].value_counts()

country_grp
United States        58049
Other                30358
Unknown              21966
China                12038
Japan                 7306
United Kingdom        4490
Korea Republic of     4162
Germany               3646
France                3161
Canada                2975
Brazil                2961
Name: count, dtype: int64

In [34]:
features = ['purchase_value', 'age', 'seconds_to_buy',
            'device_user_count', 'ip_user_count',
            'purchase_hour', 'purchase_weekday',
            'source', 'browser', 'sex', 'country_grp']

X = pd.get_dummies(df[features], drop_first=True)
y = df['class']

print(X.shape)
X.head()

(151112, 24)

   purchase_value  age  seconds_to_buy  ...  country_grp_United Kingdom  country_grp_United States  country_grp_Unknown
0              46   36       1763014.0  ...                       False                      False                 True
1              33   30       1084823.0  ...                       False                      False                 True
2              33   32        749320.0  ...                       False                      False                 True
3              33   40       7434634.0  ...                       False                      False                 True
4              55   38       1407619.0  ...                       False                      False                 True

[5 rows x 24 columns]

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

print(X_train.shape, X_test.shape)
print(y_train.mean(), y_test.mean())

(120889, 24) (30223, 24)
0.09364789186774644 0.09363729609899746

In [38]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

model = LogisticRegression(max_iter=1000)
model.fit(X_train_s, y_train)
pred = model.predict(X_test_s)

print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred, digits=3))
print('ROC-AUC:', roc_auc_score(y_test, model.predict_proba(X_test_s)[:, 1]))

[[27234   159]
 [ 1374  1456]]
              precision    recall  f1-score   support

           0      0.952     0.994     0.973     27393
           1      0.902     0.514     0.655      2830

    accuracy                          0.949     30223
   macro avg      0.927     0.754     0.814     30223
weighted avg      0.947     0.949     0.943     30223

ROC-AUC: 0.8329695536207116

In [40]:
model_bal = LogisticRegression(max_iter=1000, class_weight='balanced')
model_bal.fit(X_train_s, y_train)
pred_bal = model_bal.predict(X_test_s)

print(confusion_matrix(y_test, pred_bal))
print(classification_report(y_test, pred_bal, digits=3))

[[25578  1815]
 [  846  1984]]
              precision    recall  f1-score   support

           0      0.968     0.934     0.951     27393
           1      0.522     0.701     0.599      2830

    accuracy                          0.912     30223
   macro avg      0.745     0.817     0.775     30223
weighted avg      0.926     0.912     0.918     30223

In [42]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200, max_depth=10,
                            class_weight='balanced', random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)
pred_rf = rf.predict(X_test)

print(confusion_matrix(y_test, pred_rf))
print(classification_report(y_test, pred_rf, digits=3))
print('ROC-AUC:', roc_auc_score(y_test, rf.predict_proba(X_test)[:, 1]))

[[25736  1657]
 [  859  1971]]
              precision    recall  f1-score   support

           0      0.968     0.940     0.953     27393
           1      0.543     0.696     0.610      2830

    accuracy                          0.917     30223
   macro avg      0.755     0.818     0.782     30223
weighted avg      0.928     0.917     0.921     30223

ROC-AUC: 0.8359861737652149

In [43]:
importance = pd.Series(rf.feature_importances_, index=X.columns)
importance.sort_values(ascending=False).head(8)

device_user_count    0.396735
seconds_to_buy       0.345267
ip_user_count        0.203682
purchase_value       0.011478
age                  0.009998
purchase_hour        0.008808
purchase_weekday     0.006066
source_Direct        0.002699
dtype: float64

In [44]:
from sklearn.metrics import precision_score, recall_score

probs = rf.predict_proba(X_test)[:, 1]

for t in [0.3, 0.4, 0.5, 0.6, 0.7, 0.8]:
    pred_t = (probs >= t).astype(int)
    p = precision_score(y_test, pred_t)
    r = recall_score(y_test, pred_t)
    print(f'threshold {t}:  precision {p:.3f}  recall {r:.3f}  flagged {pred_t.sum()}')

threshold 0.3:  precision 0.524  recall 0.701  flagged 3786
threshold 0.4:  precision 0.539  recall 0.699  flagged 3670
threshold 0.5:  precision 0.543  recall 0.696  flagged 3628
threshold 0.6:  precision 0.587  recall 0.667  flagged 3217
threshold 0.7:  precision 0.931  recall 0.551  flagged 1673
threshold 0.8:  precision 1.000  recall 0.524  flagged 1484

In [45]:
import joblib
import os

os.makedirs('models', exist_ok=True)
joblib.dump(rf, 'models/fraud_rf.pkl')
joblib.dump(list(X.columns), 'models/feature_columns.pkl')
print(os.listdir('models'))

['feature_columns.pkl', 'fraud_rf.pkl']